apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flask-app.deploymentName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "flask-app.customLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
        {{- include "flask-app.customLabels" . | nindent 8 }}
    spec:
      containers:
      - name: flask-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
