{{- if .Values.monitoring.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flask-app.grafanaDatasourceConfigName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: grafana
    {{- include "flask-app.customLabels" . | nindent 4 }}
data:
  datasources.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://{{ include "flask-app.prometheusServiceName" . }}:{{ .Values.monitoring.prometheus.port }}
        isDefault: true
        editable: true
{{- end }}