{{- if .Values.monitoring.prometheus.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flask-app.prometheusDeploymentName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: prometheus
    {{- include "flask-app.customLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
        {{- include "flask-app.customLabels" . | nindent 8 }}
    spec:
      containers:
      - name: prometheus
        image: {{ .Values.monitoring.prometheus.image }}
        ports:
        - containerPort: {{ .Values.monitoring.prometheus.port }}
        resources:
          {{- toYaml .Values.monitoring.prometheus.resources | nindent 12 }}
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus
        args:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
        - '--web.console.templates=/usr/share/prometheus/consoles'
      volumes:
      - name: prometheus-config
        configMap:
          name: {{ include "flask-app.prometheusConfigName" . }}
{{- end }}