{{- if .Values.monitoring.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-app.prometheusServiceName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: prometheus
    {{- include "flask-app.customLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
  - port: {{ .Values.monitoring.prometheus.port }}
    targetPort: {{ .Values.monitoring.prometheus.port }}
    name: prometheus
{{- end }}