apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-app.serviceName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "flask-app.customLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: flask-app
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
