apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: omar-elnemr-helm-ns
  labels:
    app: prometheus
    place: iti
    name: omar-elnemr
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
      - job_name: 'flask-app'
        static_configs:
          - targets: ['flask-app-service:5000']
        metrics_path: '/metrics'
        scrape_interval: 15s
        
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: omar-elnemr-helm-ns
  labels:
    app: prometheus
    place: iti
    name: omar-elnemr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
        place: iti
        name: omar-elnemr
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.47.0
        ports:
        - containerPort: 9090
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus
        args:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
        - '--web.console.templates=/usr/share/prometheus/consoles'
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: omar-elnemr-helm-ns
  labels:
    app: prometheus
    place: iti
    name: omar-elnemr
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
    name: prometheus