    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: flask-app-servicemonitor
      namespace: monitoring
      labels:
        app: flask-app
        release: kube-prometheus-stack
    spec:
      selector:
        matchLabels:
          app.kubernetes.io/name: flask-app
          monitoring: "true"
      namespaceSelector:
        matchNames:
        - flask-app-ns
      endpoints:
      - port: web-port  # Matches the named port in service
        path: /metrics
        interval: 30s
        scrapeTimeout: 10s
        honorLabels: true
        relabelings:
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: service_name
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: kubernetes_namespace
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod_name