# Default values for flask-app.

namespace: flask-app-ns

replicaCount: 2  # Reduced for faster deployment

image:
  repository: acr.azurecr.io/flask-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80  # Changed to standard HTTP port
  targetPort: 5000  # Internal container port remains 5000
  nodePort: 30080  # Fixed NodePort for external access
  name: flask-app-service  # Explicit service name

deployment:
  name: flask-app-deployment  # Explicit deployment name

# Custom labels as specified
labels:
  place: iti
  name: omar-elnemr

# Monitoring configuration for ServiceMonitor
monitoring:
  enabled: true
  labels:
    app.kubernetes.io/name: flask-app
    monitoring: "true"
  port:
    name: web-port  # Named port for ServiceMonitor

resources:
  limits:
    memory: "128Mi"  # Reduced for faster startup
    cpu: "100m"
  requests:
    memory: "64Mi"
    cpu: "50m"